# Generated by Django 3.2.11 on 2022-01-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='tittle',
            new_name='title',
        ),
    ]
